### ISSUE TITLE
feat: Adding 'Hampel Filter' function to onebone.feature

### ISSUE THREAD

**Issue by akangel0307** [Onepredict/onebone#60]
### **시계열 구조의 데이터에서 Outlier 로 판정되는 값을 감지후, trend 를 해치지 않는 형태로 대치해주는 Filter** 
---

### 구현 목적 : 
- 모델이 학습시, 사용될 데이터에서 Outlier 가 많다면 잘못된 학습을 유도할 수 있기 때문에 해당 문제를 해결하기 위해 사용함. 

### 우려되는 점 :
- 검색해보니, Python (2021년도), R & matlab ( 2020 년도) 에 이미 구현 된 내용들이 존재하며, 직접 알고리즘을 구현해보고 다른곳에서 구현한 것들과 비교시 큰 차이가 없거나 내가 구현한게 더 별로면 정리 형식으로 바꿀 예정 
- 타 Outlier 제거 필터들에 비해 이게 어떤 차별점이나, 얼마나 성능이 좋을지 확인해봐야한다. 

### 예상되는 한계점 : 
1.  하나의 데이터에 대해서만 outlier 를 제거할 수 있다. 즉, data1 과 data2 를 비교했을때, 같은 시점에서 발생하는 Outlier 를 제거하고 싶을땐 불가능하다.
1-1) 해결 방안 : Outlier 의 index 를 추출후, 같은 시점의 Index 만 날리는 방향으로 하면됨

2. window size 를 사용자가 직접 지정하여 가장 적합한 size를 선정해야하는 수고스러움이 생길것 같다. 
2-1) 해결방안 : 사용자가 범위를 지정하면 그 범위 내에서 어떤 size 를 선정했을때, 가장 적합한지 보여주면 될 것 같다.

**Comment by Kangwhi-Kim** [comment]
기대가 되네요
