### ISSUE TITLE
snr feature 활용시 snr 외에 중간변수 필요함

### ISSUE THREAD

**Issue by fst-taewan** [Onepredict/onebone#76]
onebone.feature.snr() 함수에서 지금은 snr 값만 반환함 그런데 중간 변수가 필요함 (p, res)

![image](https://user-images.githubusercontent.com/67616448/155841280-41fce5a6-ab6e-4bb0-96cf-45ab480fbb7e.png)

**Comment by Kangwhi-Kim** [comment]
@fst-taewan @seone-kim 어떤 이유로 필요한가요? 필요하다면, p, res, snr가 동시에 사용되는 경우인가요?

**Comment by fst-taewan** [comment]
네 그렇습니다






황 태 완

Gamma Team  |  Lead



T. 02.884.1664<tel:+8228841664>     M.  010.9928.5815<tel:+821099285815>

E. ***@***.******@***.***>

A. 06160 서울특별시 강남구 테헤란로 419, 8층 (삼성동, 강남파이낸스플라자)



Digital Brain for Industrial Assets

Website<https://www.onepredict.ai/> | Linkedin<https://kr.linkedin.com/company/onepredict?challengeId=AQEja7-FeI4POgAAAXzk52E7agYK08pVxVg91TAV44SValsQWP8Yhd8iCVVlZgTobN6zFZqmOpE3-Dnblc_URpHi-Jath4zSeA&submissionId=e61fbd7e-cbfb-b316-d978-7b2d927e6945> | Facebook<https://www.facebook.com/onepredictsns/>



________________________________

**Comment by Kangwhi-Kim** [comment]
@seone-kim `p`, `res`도 같이 output으로 return할지에 대해서 어떻게 생각하시나요? 만약 `snr`가 자주 사용되고 `p`, `res`가 가끔 사용된다면 매번 함수 계산시마다 `p`, `res`를 `_`로 처리할텐데 이와 관련해서 어떤 의견이 있으실까요

**Comment by seone-kim** [comment]
저도 강휘님 말에 동의합니다. p, res 를 자주 안쓴다면 snr을 얻기 위해 매번 별도로 값을 저장해줘야할 겁니다. 
예를 들면 현재 구조에서는
arr = list()
arr.append(snr(signal, fs))
로 바로 처리가 가능한데, 리턴 값을 3개로 늘리고 snr만 쓰고 싶을 경우에는

_snr, _, _ = snr(signal, fs)
arr.append(_snr)
이런 식으로 넣어줘야하기 때문에 불편할 것이라 생각됩니다.

**Comment by fst-taewan** [comment]
안녕하세요 원프레딕트 황태완입니다.

듣고보니 현재 방식이 낫겠네요
필요시 local에서 라이브러리 수정하겠습니다

감사합니다.
황태완 드림.

황 태 완
Gamma Team  |  Lead

T. 02.884.1664     M. 010.9928.5815
E. ***@***.******@***.***>
A. 06160 서울특별시 강남구 테헤란로 419, 8층 (삼성동, 강남파이낸스플라자)

Digital Brain for Industrial Assets

***@***.***

Website<https://www.onepredict.ai/>  |  Linkedin<https://kr.linkedin.com/company/onepredict?challengeId=AQEja7-FeI4POgAAAXzk52E7agYK08pVxVg91TAV44SValsQWP8Yhd8iCVVlZgTobN6zFZqmOpE3-Dnblc_URpHi-Jath4zSeA&submissionId=e61fbd7e-cbfb-b316-d978-7b2d927e6945>  |  Facebook<https://www.facebook.com/onepredictsns/>
